### ISSUE TITLE
Set up readme

### ISSUE THREAD

**Issue by lenora4321** [CSI-280/MusicGames#1]
We have been floating around a lot of ideas about what APIs, frameworks, and services to use.  We should settle on which ones to use and detail how to set them up on a local machine and how to program with them, or at least links to their documentation on how to do these things.  This is probably an issue for two people, each focusing on a few aspects of setup that they are familiar with (like Jake with django, or whoever else with the Spotify API, preferably someone with a spotify account, if we are using that).  At the very least, we need a project summary, some basic goals, everyone's name, and links to APIs and services we will most likely be using.

**Comment by chrisbendel** [comment]
See #3 for more information i left in there too, if it helps at all

**Comment by JakeCapra** [comment]
Since we didn't have a master branch, the first push I did sent the readme to master. On the readme branch there is a readme that is actually formatted properly. So just be aware of that.

**Comment by JCastaner** [comment]
Made changes to readme on my branch. Added documentation for django and react and fixed up formatting issues a bit. Hopefully it works.

**Comment by JakeCapra** [comment]
If you check the readme branch, the readme on there has proper formatting. You also could have just pulled the readme branch instead of creating your own branch, because now if I want to add something to the readme, I don't even know what branch to use. So I guess I'll just delete the readme branch and edit off joseph_changes.
