### ISSUE TITLE
Backend Architecture of Page Connections

### ISSUE THREAD

**Issue by thomasszp** [CSI-280/MusicGames#10]
This is beyond page layouts as we should have a concrete back-end architecture before we get too far in. This might be a team decision on how we want the pages to be set up and where. Should every page branch off the homepage? Do all the pages link to eachother on the same level.

This issue should be solved with a diagram or description that lets people slot their projects and pages into the framework as a whole.

**Comment by chrisbendel** [comment]
#9 Was more of a frontend architecture issue, to avoid duplicate issues, this one can be seen as the same thing but for the backend

Research django, figure out how you will post data to the server, what endpoints you will have that expose whatever data you decide, etc

https://www.django-rest-framework.org/api-guide/routers/#api-guide would probably be a good starting point for this issue, but mock out some of the basic endpoints:

POST /login - Post endpoint for the user to authenticate
POST /user/{userId}/coins - Post endpoint to update the user's points/scores/coins/whatever currency youre using
GET /user/{userId} - Get all information for the specified user

... etc It sounds like @jbuzzell would be a good resource/helping hand for this issue (if he is working on something else) since he has experience with django

PS In the future - try to avoid duplicate issues, this one was weird because you and @JCastaner posted two issues that generally involved the same work, but it was within 5 minutes of each other - so no harm no foul. But always check the list of issues to make sure what you write up isn't already written

**Comment by thomasszp** [comment]
[Web People Outline.pdf](https://github.com/CSI-280/MusicGames/files/4384447/Web.People.Outline.pdf)

This is the basic outline i came up with for how the site should be structured.

It seems like everything should really just be branching off the homepage, and if you ever need to navigate to a different branch of the site, you should first return to the homepage.

Any input is more than welcome here as this can only be changed easily before we start slapping pages together.

**Comment by jbuzzell** [comment]
i think this belongs more in #9 than here. document flow is a UX concern, and therefore a front-end concern. this issue should be for database architecture & API planning. that said, i think this is a good start, though all three pages relating to points can likely be combined into one--there won't really be enough content on instructions/spending points to warrant a new page. depending on how much we want points to be able to be used for, that one might grow into its own thing. we also might not want to have a dedicated login page, but rather a modal on each page that allows you to log in.
