### ISSUE TITLE
Bug: TicTacToe page is blank on reload

### ISSUE THREAD

**Issue by jbuzzell** [CSI-280/MusicGames#48]
page /TicTacToe is not re-populated with content upon page reload.

steps to recreate:

- go to Games page

- click Tic Tac Toe button

- refresh page

upon completing these steps, if you open the console you should be able to observe that only the header has rendered.

**Comment by jbuzzell** [comment]
@CSI-280/web-people FYI

**Comment by jbuzzell** [comment]
this is on my current branch (not yet pushed) which was checked out from the most recent version of master (most recent commit 0d08c7c37d809bcdaaa6cd7a732a2a41bf54b37b)

**Comment by jbuzzell** [comment]
this may be an issue with the other game pages as well, i just did not work with those pages as heavily and did not take note.

**Comment by lenora4321** [comment]
I'll take a look at it

**Comment by lenora4321** [comment]
Alright, I was starting to get frustrated but I have figured it out, bless!  I moved the router up to the normal App.js thing so it could route entirely and then included the GameHub in the url for each game so that the gamenav stays on the side.  Now you can refresh all you want and it'll bring you right back to where you were.  Obviously it will start your game over if you were playing, but c'est la vie.
